### PR TITLE
vendor dependencies using govendor

### PR DESCRIPTION
**Pull request by bachp**
This makes packaging easier and follows go best practice

### CODE REVIEW

**Comment by mdlayher** [comment]
Thanks for the PR. While I agree that this application should vendor its dependencies, I'm not totally sold on govendor as the solution to that problem.

I'll think on it and make a decision later.

**Comment by mdlayher** [comment]
Thanks again for this. I'll merge as is.  Some vendoring is better than no vendoring, and it doesn't sound like `dep` is quite ready yet.

**Comment by bachp** [comment]
Thanks. I think one good thing with vendoring is that the tool can be changed easiely without much effect on the user.

**Comment by mdlayher** [comment]
Yep, you're absolutely right.  Sorry for the delay.

**Pull request merged**
