### PR TITLE
changed int64 values to float64

### PR DESCRIPTION
**Pull request by dougbishop**
Updated the vendor devices.go to the same changes submitted for the unifi client library devices.go

### CODE REVIEW

**Comment by mdlayher** [comment]
Did you just copy the changed file in?

You'll want to run `govendor fetch github.com/mdlayher/unifi` once the other PR is merged. The metadata JSON will be updated when you do.

**Comment by bachp** [comment]
@dougbishop Any update here?

**Comment by dougbishop** [comment]
Just updated the PR on the unifi library. As soon as thats merged, I can add in the changes and resubmit this PR as well.

**Comment by jasonborchardt** [comment]
Any update?  Would love to use this with my unifi APs at home.  Thanks!

**Comment by mdlayher** [comment]
The PR was merged a few weeks back so this one just needs to be updated using `govendor`.

**Pull request closed without merging**
